services:
  web:
    build: .
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media
      - static_data:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=config.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - SQLITE_NAME=/app/data/db.sqlite3

volumes:
  sqlite_data:
  media_data:
  static_data:
