# Generated by Django 4.2.30 on 2026-06-03 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microchip_number', models.CharField(blank=True, max_length=64, null=True)),
                ('blood_type', models.CharField(choices=[('unknown', 'Неизвестно'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], default='unknown', max_length=8)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_passport', to='cats.cat')),
            ],
            options={
                'ordering': ('cat__name',),
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('record_type', models.CharField(choices=[('checkup', 'Приём'), ('vaccine', 'Вакцинация'), ('treatment', 'Лечение'), ('other', 'Другое')], default='other', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='health.healthpassport')),
            ],
            options={
                'ordering': ('-event_date', '-created_at'),
            },
        ),
    ]
