# Generated by Django 4.2.30 on 2026-05-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microchip_number', models.CharField(blank=True, max_length=64, verbose_name='Номер микрочипа')),
                ('blood_type', models.CharField(choices=[('unknown', 'Неизвестно'), ('a', 'A'), ('b', 'B'), ('ab', 'AB')], default='unknown', max_length=16, verbose_name='Группа крови')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Стерилизован/кастрирован')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес, кг')),
                ('allergies', models.TextField(blank=True, verbose_name='Аллергии')),
                ('chronic_conditions', models.TextField(blank=True, verbose_name='Хронические заболевания')),
                ('veterinarian_name', models.CharField(blank=True, max_length=120, verbose_name='Ветеринар')),
                ('clinic_phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон клиники')),
                ('emergency_notes', models.TextField(blank=True, verbose_name='Экстренные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_passport', to='cats.cat', verbose_name='Кот')),
            ],
            options={
                'verbose_name': 'паспорт здоровья',
                'verbose_name_plural': 'паспорта здоровья',
                'ordering': ('cat__name',),
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('vaccination', 'Вакцинация'), ('visit', 'Визит к врачу'), ('treatment', 'Лечение'), ('medication', 'Прием лекарства'), ('analysis', 'Анализ'), ('weight', 'Контроль веса'), ('note', 'Заметка')], default='note', max_length=24, verbose_name='Тип записи')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('event_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата события')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Следующий срок')),
                ('clinic', models.CharField(blank=True, max_length=160, verbose_name='Клиника')),
                ('doctor', models.CharField(blank=True, max_length=120, verbose_name='Врач')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес, кг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='health.healthpassport', verbose_name='Паспорт')),
            ],
            options={
                'verbose_name': 'запись здоровья',
                'verbose_name_plural': 'записи здоровья',
                'ordering': ('-event_date', '-created_at'),
            },
        ),
    ]
