# Generated by Django 4.2.30 on 2026-05-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('vaccination', 'Вакцинация'), ('visit', 'Визит к врачу'), ('treatment', 'Лечение'), ('medication', 'Прием лекарств'), ('analysis', 'Анализ'), ('weight', 'Контроль веса'), ('note', 'Заметка')], default='note', max_length=24, verbose_name='Тип записи'),
        ),
    ]
