# Generated by Django 4.2.30 on 2026-05-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Кличка')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('male', 'Кот'), ('female', 'Кошка'), ('unknown', 'Неизвестно')], default='unknown', max_length=16, verbose_name='Пол')),
                ('breed', models.CharField(blank=True, max_length=120, verbose_name='Порода')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='Окрас')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'кот',
                'verbose_name_plural': 'коты',
                'ordering': ('name',),
            },
        ),
    ]
